apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hub

resources:
  - ../../../base

patches:
  - path: deployment-env.yaml
  - path: delete-oxidizedgraph-namespace.yaml
  - path: delete-base-rbac.yaml
  - path: delete-base-rbac-binding.yaml

images:
  - name: SET_BY_OVERLAY/oxidizedgraph-server
    newName: us-central1-docker.pkg.dev/gcp-lornu-ai/lornu-ai/oxidizedgraph-server
    newTag: "0.2.0"
