apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oxidizedgraph

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - worker-serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - worker-job-template.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: oxidizedgraph
      app.kubernetes.io/part-of: stevedores
      app.kubernetes.io/managed-by: kustomize
