apiVersion: v1
kind: ServiceAccount
metadata:
  name: oxidizedgraph
  namespace: oxidizedgraph
  labels:
    app.kubernetes.io/name: oxidizedgraph
  annotations:
    iam.gke.io/gcp-service-account: REPLACE_OXIDIZEDGRAPH_GCP_SA@PROJECT_ID.iam.gserviceaccount.com
