apiVersion: v1
kind: Service
metadata:
  name: oxidizedgraph
  labels:
    app.kubernetes.io/name: oxidizedgraph
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oxidizedgraph
  ports:
    - name: http
      port: 8080
      targetPort: http
