apiVersion: v1
kind: ServiceAccount
metadata:
  name: oxidizedgraph-worker
  labels:
    app.kubernetes.io/name: oxidizedgraph-worker
    app.kubernetes.io/part-of: stevedores
    agent-build/managed-by: oxidizedgraph
