apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxidizedgraph
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: oxidizedgraph
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
